name: PlayerChat
main: cn.handyplus.chat.PlayerChat
version: 1.2.6
author: handy
api-version: 1.13
softdepend: [ PlaceholderAPI ]
website: https://ricedoc.handyplus.cn/wiki/PlayerChat/log/
description: 一款有点好用的聊天插件
folia-supported: true
commands:
  playerChat:
    description: 一款有点好用的聊天插件
    aliases: [ plc ]
  lb:
    description: 一款有点好用的聊天插件
    aliases: [ lb ]
permissions:
  playerChat.*:
    description: 一款有点好用的聊天插件
    children:
      playerChat.reload: true
      playerChat.give: true
      playerChat.take: true
      playerChat.set: true
      playerChat.look: true
      playerChat.color: true
      playerChat.channel: true
      playerChat.item: true
      playerChat.tell: true
      playerChat.clearBossBar: true
  playerChat.reload:
    description: 重新加载配置
    default: op
  playerChat.give:
    description: 给予喇叭
    default: op
  playerChat.take:
    description: 拿走喇叭
    default: op
  playerChat.set:
    description: 设置喇叭
    default: op
  playerChat.look:
    description: 查看喇叭
    default: op
  playerChat.color:
    description: 颜色权限
    default: op
  playerChat.channel:
    description: 切换频道
    default: op
  playerChat.item:
    description: 查看展示物品
    default: true
  playerChat.chat.default:
    description: 默认频道查看权限
    default: true
  playerChat.use.default:
    description: 默认频道使用权限
    default: true
  playerChat.tell:
    description: 私聊权限
    default: op
  playerChat.chat.tell:
    description: 私信频道查看权限
    default: true
  playerChat.use.tell:
    description: 私信频道使用权限
    default: op
  playerChat.clearBossBar:
    description: 移除全部BossBar消息
    default: op